version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
